### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by alvyn279** [alvyn279/discord-events#1]
- Infra:
    - [x] Containerize Java application
    - [x] Create `ApplicationLoadBalancedEc2Service `
    - [x] ~Switch to public ECR repository~
    - [x] Set table name in CDK (maybe env var ?)
    - [x] IMPORTANT: ~Check why health checks fail so often with task definition~
    - [x] IMPORTANT: Downgrade infrastructure to normal EC2 task without the load balancer and health
    - [x] Why do some commands do not go through ?
        - [x] Set up logs for container execution
    - [x] Add log stream to container execution
    - [x] NAT Gateway spendings (almost 2$ a day)
        - [x] Documentation[[1](https://aws.amazon.com/premiumsupport/knowledge-center/vpc-reduce-nat-gateway-transfer-costs/)][[2](https://docs.aws.amazon.com/vpc/latest/userguide/vpce-gateway.html#gateway-endpoint-pricing)] We only need one public subnet that contains our single instance. Our route tables point to vpc endpoints for ddb interaction.
![desired low-level infra](https://docs.aws.amazon.com/vpc/latest/userguide/images/vpc-endpoint-s3-diagram.png)
        - [x] VPC endpoints to DDB
        - [x] Internet Gateway for Discord API WebSocket
    - [x] Segregate infra into test DDB and prod DDB tables 
    - [ ] Hot reload with docker-compose volumes
    - [ ] DDB index on `messageId` ?
    - [ ] Restart container [on failure](https://docs.docker.com/config/containers/start-containers-automatically/)
    - [ ] Look into SSM for secrets
    - [ ] GitHub Action to build/deploy/update ECS service (see if this is necessary)
    - [ ] Health check server
    - [ ] Dockerize CDK
- Bot:
    - [x] Fix async issue on ping and create 
    - [x] Support multiple servers for DDB by adding `guildId` as attribute (redesign DDB)
    - [x] List events
        - [x] list upcoming
        - [x] list between range
        - [x] list on date
        - [x] add `created by` in title of list item
    - [x] Error handling (oops message)
    - [x] ~Extract `CommandReaction` into a class other than `DiscordEventsBot`~
    - [x] Help command (sample usage)
    - [x] Manage personal events
        - [x] view my-events 
        - [x] return message id for delete
        - [x] change title of bot response to have username of creator
        - [x] ~Send PM for my-events instead of in public channel~
    - [x] Delete event
        - [x] Delete multiple inline
    - [x] ~Describing events with reactions~
    - [x] optional descriptions
    - [x] Reminder messages
        - [x] simple reminder
        - [x] status command that tells which text channel is subscribed to the reminders 
        - [x] ~Make notifying delay configurable~
        - [x] current implementation won't work for reminding multiple servers !!
        - [ ] Support distributed systems arch
                Right now the singleton pattern for the scheduler only allows there to be a single instance servicing the bot at all times. 
            Look into https://github.com/Discord4J/connect
    - [x] Empty events message
    - [x] ~Refactor `ListDiscordEventsCommandArgs` into more specific classes for each ddb repo op~
    - [ ] Attendees
        - [x] choose best way to store this info
        - [x] string set must not be empty at write time
        - [x] write repo functions
        - [x] `!attend-event` + emoji reactions
        - [x] Single-liner should be changed to show each event
        - [x] remove reaction
        - [ ] mentions
        - [ ] add to every list function
        - [ ] help, readme
    - [ ] Important: Support more than one timezones (setting it manually)
    - [ ] Cache guild members fetch
    - [ ] Pluggable into any other Discord4J bot
    - [ ] Google Calendar and others
- Documentation:
    - [x] Screenshots in README 
- Tools:
    - [ ] linter for cdk

### Takeaways

1. For single-task services, setting the desired tasks count matters at creation and at deploy time
_Solution_: Set to 0 before update [as per docs](https://aws.amazon.com/premiumsupport/knowledge-center/ecs-service-stuck-update-status/).
Better _solution_: **USE DAEMON MODE** !!
https://github.com/aws/aws-cdk/issues/5215
https://github.com/aws/aws-cdk/pull/12223
https://github.com/aws/aws-cdk/issues/11951
2. NAT Gateway for persistent connections will eat your wallet.

**Comment by Stochastic-Adventure** [comment]
Hi!

This is a wonderful repo as I am looking to build a similar bot with AWS ECS as well.

Just curious what is the cost after removing the NAT Gateway?

Thanks in advance!

**Comment by alvyn279** [comment]
Hey @Stochastic-Adventure ,

I recall being charged around 2$/day solely for bot heartbeat (every 1-2 mins) traffic going through the NAT Gateway.

I think running continuously a single image of the bot cost around 8-10$ a month or so.

**Comment by Stochastic-Adventure** [comment]
Thanks!

$8-10 / month is reasonable.

One more question: did you use AWS Secrets Manager to store bot token?

**Comment by alvyn279** [comment]
> Thanks!
> 
> $8-10 / month is reasonable.
> 
> One more question: did you use AWS Secrets Manager to store bot token?


Nope, I have it as an env var, but modifying the bot to make use of SM would probably be best practice here. Might be [cheap too](https://aws.amazon.com/secrets-manager/pricing/).

This being said, the current bot setup I have makes it quite hard to attack the secret as env var on the containerized app. The ec2 instance has no public IP, being in its own VPC, and what not.
